### ISSUE TITLE
How  to run relation_extractor.py parallelly?

### ISSUE THREAD

**Issue by Gyyyym** [rutvik5/knowledge-graph#1]
I want to run relation_extractor.py parallelly. but it   gives an error。

Extracting relations for 1001_q_context.txt
Traceback (most recent call last):
  File "main.py", line 152, in <module>
    exit(main(argv))
  File "main.py", line 146, in main
    entities_relations = stanford_ie(filename, verbose, generate_graphviz)
  File "main.py", line 124, in stanford_ie
    with open(out, 'r') as output_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/openie/out.txt'

How should I solve it？Thank you very much .

**Comment by Dhruva0101** [comment]
were you able to solve the issue. Can you please help me out if you have
?
